[2022-11-18 06:50:42,429] {processor.py:163} INFO - Started process (PID=46) to work on /opt/airflow/dags/queue_reader.py
[2022-11-18 06:50:42,470] {processor.py:642} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-18 06:50:42,476] {logging_mixin.py:109} INFO - [2022-11-18 06:50:42,476] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-18 06:50:44,512] {logging_mixin.py:109} INFO - [2022-11-18 06:50:44,511] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from airflow_multi_dagrun.operators import TriggerMultiDagRunOperator
ModuleNotFoundError: No module named 'airflow_multi_dagrun'
[2022-11-18 06:50:44,558] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-18 06:50:44,583] {processor.py:171} INFO - Processing /opt/airflow/dags/queue_reader.py took 2.279 seconds
[2022-11-18 06:51:37,851] {processor.py:163} INFO - Started process (PID=82) to work on /opt/airflow/dags/queue_reader.py
[2022-11-18 06:51:37,881] {processor.py:642} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-18 06:51:37,907] {logging_mixin.py:109} INFO - [2022-11-18 06:51:37,907] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-18 06:51:39,258] {logging_mixin.py:109} INFO - [2022-11-18 06:51:39,237] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from airflow_multi_dagrun.operators import TriggerMultiDagRunOperator
ModuleNotFoundError: No module named 'airflow_multi_dagrun'
[2022-11-18 06:51:39,388] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-18 06:51:39,478] {processor.py:171} INFO - Processing /opt/airflow/dags/queue_reader.py took 1.655 seconds
[2022-11-18 06:53:38,750] {processor.py:163} INFO - Started process (PID=230) to work on /opt/airflow/dags/queue_reader.py
[2022-11-18 06:53:38,752] {processor.py:642} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-18 06:53:38,755] {logging_mixin.py:109} INFO - [2022-11-18 06:53:38,754] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-18 06:53:38,946] {logging_mixin.py:109} INFO - [2022-11-18 06:53:38,945] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from airflow_multi_dagrun.operators import TriggerMultiDagRunOperator
ModuleNotFoundError: No module named 'airflow_multi_dagrun'
[2022-11-18 06:53:38,974] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-18 06:53:38,991] {processor.py:171} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.259 seconds
[2022-11-18 06:54:09,197] {processor.py:163} INFO - Started process (PID=277) to work on /opt/airflow/dags/queue_reader.py
[2022-11-18 06:54:09,206] {processor.py:642} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-18 06:54:09,208] {logging_mixin.py:109} INFO - [2022-11-18 06:54:09,208] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-18 06:54:09,351] {logging_mixin.py:109} INFO - [2022-11-18 06:54:09,350] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from airflow_multi_dagrun.operators import TriggerMultiDagRunOperator
ModuleNotFoundError: No module named 'airflow_multi_dagrun'
[2022-11-18 06:54:09,369] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-18 06:54:09,381] {processor.py:171} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.230 seconds
[2022-11-18 06:54:39,419] {processor.py:163} INFO - Started process (PID=331) to work on /opt/airflow/dags/queue_reader.py
[2022-11-18 06:54:39,421] {processor.py:642} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-18 06:54:39,422] {logging_mixin.py:109} INFO - [2022-11-18 06:54:39,422] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-18 06:54:39,604] {logging_mixin.py:109} INFO - [2022-11-18 06:54:39,603] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from airflow_multi_dagrun.operators import TriggerMultiDagRunOperator
ModuleNotFoundError: No module named 'airflow_multi_dagrun'
[2022-11-18 06:54:39,631] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-18 06:54:39,647] {processor.py:171} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.233 seconds
[2022-11-18 06:55:09,844] {processor.py:163} INFO - Started process (PID=382) to work on /opt/airflow/dags/queue_reader.py
[2022-11-18 06:55:09,855] {processor.py:642} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-18 06:55:09,859] {logging_mixin.py:109} INFO - [2022-11-18 06:55:09,858] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-18 06:55:10,337] {logging_mixin.py:109} INFO - [2022-11-18 06:55:10,322] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from airflow_multi_dagrun.operators import TriggerMultiDagRunOperator
ModuleNotFoundError: No module named 'airflow_multi_dagrun'
[2022-11-18 06:55:10,394] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-18 06:55:10,426] {processor.py:171} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.597 seconds
[2022-11-18 06:55:41,371] {processor.py:163} INFO - Started process (PID=434) to work on /opt/airflow/dags/queue_reader.py
[2022-11-18 06:55:41,372] {processor.py:642} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-18 06:55:41,373] {logging_mixin.py:109} INFO - [2022-11-18 06:55:41,373] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-18 06:55:41,503] {logging_mixin.py:109} INFO - [2022-11-18 06:55:41,501] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from airflow_multi_dagrun.operators import TriggerMultiDagRunOperator
ModuleNotFoundError: No module named 'airflow_multi_dagrun'
[2022-11-18 06:55:41,520] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-18 06:55:41,530] {processor.py:171} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.163 seconds
[2022-11-18 06:56:11,696] {processor.py:163} INFO - Started process (PID=486) to work on /opt/airflow/dags/queue_reader.py
[2022-11-18 06:56:11,698] {processor.py:642} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-18 06:56:11,699] {logging_mixin.py:109} INFO - [2022-11-18 06:56:11,699] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-18 06:56:11,850] {logging_mixin.py:109} INFO - [2022-11-18 06:56:11,849] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from airflow_multi_dagrun.operators import TriggerMultiDagRunOperator
ModuleNotFoundError: No module named 'airflow_multi_dagrun'
[2022-11-18 06:56:11,867] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-18 06:56:11,877] {processor.py:171} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.186 seconds
[2022-11-18 06:56:42,398] {processor.py:163} INFO - Started process (PID=538) to work on /opt/airflow/dags/queue_reader.py
[2022-11-18 06:56:42,400] {processor.py:642} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-18 06:56:42,401] {logging_mixin.py:109} INFO - [2022-11-18 06:56:42,401] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-18 06:56:42,577] {logging_mixin.py:109} INFO - [2022-11-18 06:56:42,575] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from airflow_multi_dagrun.operators import TriggerMultiDagRunOperator
ModuleNotFoundError: No module named 'airflow_multi_dagrun'
[2022-11-18 06:56:42,600] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-18 06:56:42,613] {processor.py:171} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.220 seconds
[2022-11-18 06:57:13,063] {processor.py:163} INFO - Started process (PID=589) to work on /opt/airflow/dags/queue_reader.py
[2022-11-18 06:57:13,065] {processor.py:642} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-18 06:57:13,067] {logging_mixin.py:109} INFO - [2022-11-18 06:57:13,067] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-18 06:57:13,298] {logging_mixin.py:109} INFO - [2022-11-18 06:57:13,292] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from airflow_multi_dagrun.operators import TriggerMultiDagRunOperator
ModuleNotFoundError: No module named 'airflow_multi_dagrun'
[2022-11-18 06:57:13,334] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-18 06:57:13,377] {processor.py:171} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.321 seconds
[2022-11-18 06:57:44,294] {processor.py:163} INFO - Started process (PID=642) to work on /opt/airflow/dags/queue_reader.py
[2022-11-18 06:57:44,296] {processor.py:642} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-18 06:57:44,297] {logging_mixin.py:109} INFO - [2022-11-18 06:57:44,297] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-18 06:57:44,452] {logging_mixin.py:109} INFO - [2022-11-18 06:57:44,448] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from airflow_multi_dagrun.operators import TriggerMultiDagRunOperator
ModuleNotFoundError: No module named 'airflow_multi_dagrun'
[2022-11-18 06:57:44,473] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-18 06:57:44,487] {processor.py:171} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.199 seconds
[2022-11-18 06:58:15,356] {processor.py:163} INFO - Started process (PID=696) to work on /opt/airflow/dags/queue_reader.py
[2022-11-18 06:58:15,360] {processor.py:642} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-18 06:58:15,361] {logging_mixin.py:109} INFO - [2022-11-18 06:58:15,361] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-18 06:58:15,485] {logging_mixin.py:109} INFO - [2022-11-18 06:58:15,483] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from airflow_multi_dagrun.operators import TriggerMultiDagRunOperator
ModuleNotFoundError: No module named 'airflow_multi_dagrun'
[2022-11-18 06:58:15,546] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-18 06:58:15,585] {processor.py:171} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.239 seconds
[2022-11-18 06:58:45,808] {processor.py:163} INFO - Started process (PID=749) to work on /opt/airflow/dags/queue_reader.py
[2022-11-18 06:58:45,816] {processor.py:642} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-18 06:58:45,818] {logging_mixin.py:109} INFO - [2022-11-18 06:58:45,818] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-18 06:58:46,086] {logging_mixin.py:109} INFO - [2022-11-18 06:58:46,083] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from airflow_multi_dagrun.operators import TriggerMultiDagRunOperator
ModuleNotFoundError: No module named 'airflow_multi_dagrun'
[2022-11-18 06:58:46,134] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-18 06:58:46,160] {processor.py:171} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.369 seconds
[2022-11-18 06:59:16,372] {processor.py:163} INFO - Started process (PID=800) to work on /opt/airflow/dags/queue_reader.py
[2022-11-18 06:59:16,374] {processor.py:642} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-18 06:59:16,376] {logging_mixin.py:109} INFO - [2022-11-18 06:59:16,376] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-18 06:59:16,529] {logging_mixin.py:109} INFO - [2022-11-18 06:59:16,528] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from airflow_multi_dagrun.operators import TriggerMultiDagRunOperator
ModuleNotFoundError: No module named 'airflow_multi_dagrun'
[2022-11-18 06:59:16,547] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-18 06:59:16,561] {processor.py:171} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.195 seconds
[2022-11-18 06:59:46,793] {processor.py:163} INFO - Started process (PID=852) to work on /opt/airflow/dags/queue_reader.py
[2022-11-18 06:59:46,799] {processor.py:642} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-18 06:59:46,800] {logging_mixin.py:109} INFO - [2022-11-18 06:59:46,800] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-18 06:59:47,581] {logging_mixin.py:109} INFO - [2022-11-18 06:59:47,578] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from airflow_multi_dagrun.operators import TriggerMultiDagRunOperator
ModuleNotFoundError: No module named 'airflow_multi_dagrun'
[2022-11-18 06:59:47,641] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-18 06:59:47,671] {processor.py:171} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.890 seconds
[2022-11-18 07:00:17,919] {processor.py:163} INFO - Started process (PID=904) to work on /opt/airflow/dags/queue_reader.py
[2022-11-18 07:00:17,921] {processor.py:642} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-18 07:00:17,922] {logging_mixin.py:109} INFO - [2022-11-18 07:00:17,922] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-18 07:00:18,062] {logging_mixin.py:109} INFO - [2022-11-18 07:00:18,061] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from airflow_multi_dagrun.operators import TriggerMultiDagRunOperator
ModuleNotFoundError: No module named 'airflow_multi_dagrun'
[2022-11-18 07:00:18,082] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-18 07:00:18,092] {processor.py:171} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.180 seconds
[2022-11-18 07:00:48,240] {processor.py:163} INFO - Started process (PID=957) to work on /opt/airflow/dags/queue_reader.py
[2022-11-18 07:00:48,241] {processor.py:642} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-18 07:00:48,242] {logging_mixin.py:109} INFO - [2022-11-18 07:00:48,242] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-18 07:00:48,360] {logging_mixin.py:109} INFO - [2022-11-18 07:00:48,359] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from airflow_multi_dagrun.operators import TriggerMultiDagRunOperator
ModuleNotFoundError: No module named 'airflow_multi_dagrun'
[2022-11-18 07:00:48,376] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-18 07:00:48,386] {processor.py:171} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.151 seconds
[2022-11-18 07:01:18,838] {processor.py:163} INFO - Started process (PID=1008) to work on /opt/airflow/dags/queue_reader.py
[2022-11-18 07:01:18,840] {processor.py:642} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-18 07:01:18,841] {logging_mixin.py:109} INFO - [2022-11-18 07:01:18,840] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-18 07:01:19,029] {logging_mixin.py:109} INFO - [2022-11-18 07:01:19,027] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from airflow_multi_dagrun.operators import TriggerMultiDagRunOperator
ModuleNotFoundError: No module named 'airflow_multi_dagrun'
[2022-11-18 07:01:19,055] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-18 07:01:19,065] {processor.py:171} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.232 seconds
[2022-11-18 07:01:49,558] {processor.py:163} INFO - Started process (PID=1060) to work on /opt/airflow/dags/queue_reader.py
[2022-11-18 07:01:49,560] {processor.py:642} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-18 07:01:49,561] {logging_mixin.py:109} INFO - [2022-11-18 07:01:49,560] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-18 07:01:49,730] {logging_mixin.py:109} INFO - [2022-11-18 07:01:49,728] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from airflow_multi_dagrun.operators import TriggerMultiDagRunOperator
ModuleNotFoundError: No module named 'airflow_multi_dagrun'
[2022-11-18 07:01:49,760] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-18 07:01:49,772] {processor.py:171} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.219 seconds
[2022-11-18 07:02:20,327] {processor.py:163} INFO - Started process (PID=1112) to work on /opt/airflow/dags/queue_reader.py
[2022-11-18 07:02:20,331] {processor.py:642} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-18 07:02:20,344] {logging_mixin.py:109} INFO - [2022-11-18 07:02:20,340] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-18 07:02:20,576] {logging_mixin.py:109} INFO - [2022-11-18 07:02:20,574] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from airflow_multi_dagrun.operators import TriggerMultiDagRunOperator
ModuleNotFoundError: No module named 'airflow_multi_dagrun'
[2022-11-18 07:02:20,617] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-18 07:02:20,648] {processor.py:171} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.327 seconds
[2022-11-18 07:02:50,722] {processor.py:163} INFO - Started process (PID=1164) to work on /opt/airflow/dags/queue_reader.py
[2022-11-18 07:02:50,732] {processor.py:642} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-18 07:02:50,734] {logging_mixin.py:109} INFO - [2022-11-18 07:02:50,733] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-18 07:02:50,992] {logging_mixin.py:109} INFO - [2022-11-18 07:02:50,990] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from airflow_multi_dagrun.operators import TriggerMultiDagRunOperator
ModuleNotFoundError: No module named 'airflow_multi_dagrun'
[2022-11-18 07:02:51,014] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-18 07:02:51,026] {processor.py:171} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.315 seconds
[2022-11-18 07:03:21,130] {processor.py:163} INFO - Started process (PID=1215) to work on /opt/airflow/dags/queue_reader.py
[2022-11-18 07:03:21,148] {processor.py:642} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-18 07:03:21,155] {logging_mixin.py:109} INFO - [2022-11-18 07:03:21,155] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-18 07:03:21,596] {logging_mixin.py:109} INFO - [2022-11-18 07:03:21,589] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from airflow_multi_dagrun.operators import TriggerMultiDagRunOperator
ModuleNotFoundError: No module named 'airflow_multi_dagrun'
[2022-11-18 07:03:21,632] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-18 07:03:21,658] {processor.py:171} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.557 seconds
[2022-11-18 07:03:52,375] {processor.py:163} INFO - Started process (PID=1268) to work on /opt/airflow/dags/queue_reader.py
[2022-11-18 07:03:52,377] {processor.py:642} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-18 07:03:52,378] {logging_mixin.py:109} INFO - [2022-11-18 07:03:52,378] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-18 07:03:52,581] {logging_mixin.py:109} INFO - [2022-11-18 07:03:52,579] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from airflow_multi_dagrun.operators import TriggerMultiDagRunOperator
ModuleNotFoundError: No module named 'airflow_multi_dagrun'
[2022-11-18 07:03:52,605] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-18 07:03:52,618] {processor.py:171} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.250 seconds
[2022-11-18 07:04:23,350] {processor.py:163} INFO - Started process (PID=1320) to work on /opt/airflow/dags/queue_reader.py
[2022-11-18 07:04:23,352] {processor.py:642} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-18 07:04:23,358] {logging_mixin.py:109} INFO - [2022-11-18 07:04:23,358] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-18 07:04:23,561] {logging_mixin.py:109} INFO - [2022-11-18 07:04:23,553] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from airflow_multi_dagrun.operators import TriggerMultiDagRunOperator
ModuleNotFoundError: No module named 'airflow_multi_dagrun'
[2022-11-18 07:04:23,599] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-18 07:04:23,618] {processor.py:171} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.277 seconds
[2022-11-18 07:04:32,794] {processor.py:163} INFO - Started process (PID=1350) to work on /opt/airflow/dags/queue_reader.py
[2022-11-18 07:04:32,801] {processor.py:642} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-18 07:04:32,803] {logging_mixin.py:109} INFO - [2022-11-18 07:04:32,802] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-18 07:04:33,067] {logging_mixin.py:109} INFO - [2022-11-18 07:04:33,058] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from airflow_multi_dagrun.operators import TriggerMultiDagRunOperator
ModuleNotFoundError: No module named 'airflow_multi_dagrun'
[2022-11-18 07:04:33,101] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-18 07:04:33,130] {processor.py:171} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.343 seconds
[2022-11-18 07:05:04,065] {processor.py:163} INFO - Started process (PID=1403) to work on /opt/airflow/dags/queue_reader.py
[2022-11-18 07:05:04,067] {processor.py:642} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-18 07:05:04,068] {logging_mixin.py:109} INFO - [2022-11-18 07:05:04,068] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-18 07:05:04,312] {logging_mixin.py:109} INFO - [2022-11-18 07:05:04,311] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from airflow_multi_dagrun.operators import TriggerMultiDagRunOperator
ModuleNotFoundError: No module named 'airflow_multi_dagrun'
[2022-11-18 07:05:04,336] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-18 07:05:04,348] {processor.py:171} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.293 seconds
[2022-11-18 07:05:09,986] {processor.py:163} INFO - Started process (PID=1410) to work on /opt/airflow/dags/queue_reader.py
[2022-11-18 07:05:10,000] {processor.py:642} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-18 07:05:10,004] {logging_mixin.py:109} INFO - [2022-11-18 07:05:10,004] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-18 07:05:10,663] {logging_mixin.py:109} INFO - [2022-11-18 07:05:10,650] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from airflow_multi_dagrun.operators import TriggerMultiDagRunOperator
ModuleNotFoundError: No module named 'airflow_multi_dagrun'
[2022-11-18 07:05:10,754] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-18 07:05:10,805] {processor.py:171} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.851 seconds
[2022-11-18 07:05:41,524] {processor.py:163} INFO - Started process (PID=1462) to work on /opt/airflow/dags/queue_reader.py
[2022-11-18 07:05:41,528] {processor.py:642} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-18 07:05:41,530] {logging_mixin.py:109} INFO - [2022-11-18 07:05:41,530] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-18 07:05:41,835] {logging_mixin.py:109} INFO - [2022-11-18 07:05:41,830] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from airflow_multi_dagrun.operators import TriggerMultiDagRunOperator
ModuleNotFoundError: No module named 'airflow_multi_dagrun'
[2022-11-18 07:05:41,875] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-18 07:05:41,906] {processor.py:171} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.400 seconds
[2022-11-18 07:06:13,729] {processor.py:163} INFO - Started process (PID=1515) to work on /opt/airflow/dags/queue_reader.py
[2022-11-18 07:06:13,735] {processor.py:642} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-18 07:06:13,736] {logging_mixin.py:109} INFO - [2022-11-18 07:06:13,736] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-18 07:06:13,967] {logging_mixin.py:109} INFO - [2022-11-18 07:06:13,965] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from airflow_multi_dagrun.operators import TriggerMultiDagRunOperator
ModuleNotFoundError: No module named 'airflow_multi_dagrun'
[2022-11-18 07:06:14,004] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-18 07:06:14,030] {processor.py:171} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.309 seconds
[2022-11-18 07:06:44,233] {processor.py:163} INFO - Started process (PID=1561) to work on /opt/airflow/dags/queue_reader.py
[2022-11-18 07:06:44,243] {processor.py:642} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-18 07:06:44,250] {logging_mixin.py:109} INFO - [2022-11-18 07:06:44,250] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-18 07:06:44,520] {logging_mixin.py:109} INFO - [2022-11-18 07:06:44,514] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from airflow_multi_dagrun.operators import TriggerMultiDagRunOperator
ModuleNotFoundError: No module named 'airflow_multi_dagrun'
[2022-11-18 07:06:44,556] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-18 07:06:44,575] {processor.py:171} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.348 seconds
[2022-11-18 07:07:16,909] {processor.py:163} INFO - Started process (PID=1592) to work on /opt/airflow/dags/queue_reader.py
[2022-11-18 07:07:16,912] {processor.py:642} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-18 07:07:16,919] {logging_mixin.py:109} INFO - [2022-11-18 07:07:16,919] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-18 07:07:18,072] {logging_mixin.py:109} INFO - [2022-11-18 07:07:18,056] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from airflow_multi_dagrun.operators import TriggerMultiDagRunOperator
ModuleNotFoundError: No module named 'airflow_multi_dagrun'
[2022-11-18 07:07:18,199] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-18 07:07:18,274] {processor.py:171} INFO - Processing /opt/airflow/dags/queue_reader.py took 1.410 seconds
[2022-11-18 07:07:48,604] {processor.py:163} INFO - Started process (PID=1644) to work on /opt/airflow/dags/queue_reader.py
[2022-11-18 07:07:48,607] {processor.py:642} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-18 07:07:48,609] {logging_mixin.py:109} INFO - [2022-11-18 07:07:48,609] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-18 07:07:48,776] {logging_mixin.py:109} INFO - [2022-11-18 07:07:48,774] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from airflow_multi_dagrun.operators import TriggerMultiDagRunOperator
ModuleNotFoundError: No module named 'airflow_multi_dagrun'
[2022-11-18 07:07:48,798] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-18 07:07:48,810] {processor.py:171} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.214 seconds
[2022-11-18 07:08:19,034] {processor.py:163} INFO - Started process (PID=1705) to work on /opt/airflow/dags/queue_reader.py
[2022-11-18 07:08:19,037] {processor.py:642} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-18 07:08:19,038] {logging_mixin.py:109} INFO - [2022-11-18 07:08:19,038] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-18 07:08:19,192] {logging_mixin.py:109} INFO - [2022-11-18 07:08:19,191] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from airflow_multi_dagrun.operators import TriggerMultiDagRunOperator
ModuleNotFoundError: No module named 'airflow_multi_dagrun'
[2022-11-18 07:08:19,214] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-18 07:08:19,227] {processor.py:171} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.207 seconds
[2022-11-18 07:08:49,346] {processor.py:163} INFO - Started process (PID=1753) to work on /opt/airflow/dags/queue_reader.py
[2022-11-18 07:08:49,355] {processor.py:642} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-18 07:08:49,357] {logging_mixin.py:109} INFO - [2022-11-18 07:08:49,356] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-18 07:08:49,892] {logging_mixin.py:109} INFO - [2022-11-18 07:08:49,875] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from airflow_multi_dagrun.operators import TriggerMultiDagRunOperator
ModuleNotFoundError: No module named 'airflow_multi_dagrun'
[2022-11-18 07:08:49,943] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-18 07:08:49,971] {processor.py:171} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.640 seconds
[2022-11-18 07:09:20,356] {processor.py:163} INFO - Started process (PID=1798) to work on /opt/airflow/dags/queue_reader.py
[2022-11-18 07:09:20,363] {processor.py:642} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-18 07:09:20,364] {logging_mixin.py:109} INFO - [2022-11-18 07:09:20,364] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-18 07:09:20,808] {logging_mixin.py:109} INFO - [2022-11-18 07:09:20,805] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from airflow_multi_dagrun.operators import TriggerMultiDagRunOperator
ModuleNotFoundError: No module named 'airflow_multi_dagrun'
[2022-11-18 07:09:20,946] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-18 07:09:21,004] {processor.py:171} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.658 seconds
[2022-11-18 07:10:36,851] {processor.py:163} INFO - Started process (PID=1864) to work on /opt/airflow/dags/queue_reader.py
[2022-11-18 07:10:36,916] {processor.py:642} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-18 07:10:36,925] {logging_mixin.py:109} INFO - [2022-11-18 07:10:36,924] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-18 07:10:39,641] {logging_mixin.py:109} INFO - [2022-11-18 07:10:39,567] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from airflow_multi_dagrun.operators import TriggerMultiDagRunOperator
ModuleNotFoundError: No module named 'airflow_multi_dagrun'
[2022-11-18 07:10:39,904] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-18 07:10:40,073] {processor.py:171} INFO - Processing /opt/airflow/dags/queue_reader.py took 3.303 seconds
[2022-11-18 07:11:14,957] {processor.py:163} INFO - Started process (PID=1911) to work on /opt/airflow/dags/queue_reader.py
[2022-11-18 07:11:14,964] {processor.py:642} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-18 07:11:14,966] {logging_mixin.py:109} INFO - [2022-11-18 07:11:14,966] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-18 07:11:16,704] {logging_mixin.py:109} INFO - [2022-11-18 07:11:16,694] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from airflow_multi_dagrun.operators import TriggerMultiDagRunOperator
ModuleNotFoundError: No module named 'airflow_multi_dagrun'
[2022-11-18 07:11:16,834] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-18 07:11:16,905] {processor.py:171} INFO - Processing /opt/airflow/dags/queue_reader.py took 1.961 seconds
[2022-11-18 07:11:48,092] {processor.py:163} INFO - Started process (PID=1965) to work on /opt/airflow/dags/queue_reader.py
[2022-11-18 07:11:48,103] {processor.py:642} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-18 07:11:48,105] {logging_mixin.py:109} INFO - [2022-11-18 07:11:48,105] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-18 07:11:48,399] {logging_mixin.py:109} INFO - [2022-11-18 07:11:48,398] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from airflow_multi_dagrun.operators import TriggerMultiDagRunOperator
ModuleNotFoundError: No module named 'airflow_multi_dagrun'
[2022-11-18 07:11:48,438] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-18 07:11:48,475] {processor.py:171} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.398 seconds
[2022-11-18 07:12:18,680] {processor.py:163} INFO - Started process (PID=2017) to work on /opt/airflow/dags/queue_reader.py
[2022-11-18 07:12:18,683] {processor.py:642} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-18 07:12:18,684] {logging_mixin.py:109} INFO - [2022-11-18 07:12:18,684] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-18 07:12:19,362] {logging_mixin.py:109} INFO - [2022-11-18 07:12:19,358] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from airflow_multi_dagrun.operators import TriggerMultiDagRunOperator
ModuleNotFoundError: No module named 'airflow_multi_dagrun'
[2022-11-18 07:12:19,426] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-18 07:12:19,479] {processor.py:171} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.809 seconds
[2022-11-18 07:12:49,818] {processor.py:163} INFO - Started process (PID=2061) to work on /opt/airflow/dags/queue_reader.py
[2022-11-18 07:12:49,824] {processor.py:642} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-18 07:12:49,828] {logging_mixin.py:109} INFO - [2022-11-18 07:12:49,827] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-18 07:12:50,349] {logging_mixin.py:109} INFO - [2022-11-18 07:12:50,328] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from airflow_multi_dagrun.operators import TriggerMultiDagRunOperator
ModuleNotFoundError: No module named 'airflow_multi_dagrun'
[2022-11-18 07:12:50,725] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-18 07:12:50,794] {processor.py:171} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.988 seconds
[2022-11-18 07:13:21,748] {processor.py:163} INFO - Started process (PID=2115) to work on /opt/airflow/dags/queue_reader.py
[2022-11-18 07:13:21,761] {processor.py:642} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-18 07:13:21,764] {logging_mixin.py:109} INFO - [2022-11-18 07:13:21,764] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-18 07:13:22,513] {logging_mixin.py:109} INFO - [2022-11-18 07:13:22,503] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from airflow_multi_dagrun.operators import TriggerMultiDagRunOperator
ModuleNotFoundError: No module named 'airflow_multi_dagrun'
[2022-11-18 07:13:22,579] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-18 07:13:22,634] {processor.py:171} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.918 seconds
[2022-11-18 07:13:53,226] {processor.py:163} INFO - Started process (PID=2166) to work on /opt/airflow/dags/queue_reader.py
[2022-11-18 07:13:53,230] {processor.py:642} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-18 07:13:53,241] {logging_mixin.py:109} INFO - [2022-11-18 07:13:53,241] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-18 07:13:53,471] {logging_mixin.py:109} INFO - [2022-11-18 07:13:53,470] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from airflow_multi_dagrun.operators import TriggerMultiDagRunOperator
ModuleNotFoundError: No module named 'airflow_multi_dagrun'
[2022-11-18 07:13:53,493] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-18 07:13:53,504] {processor.py:171} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.286 seconds
[2022-11-18 07:14:24,203] {processor.py:163} INFO - Started process (PID=2219) to work on /opt/airflow/dags/queue_reader.py
[2022-11-18 07:14:24,217] {processor.py:642} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-18 07:14:24,218] {logging_mixin.py:109} INFO - [2022-11-18 07:14:24,218] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-18 07:14:24,619] {logging_mixin.py:109} INFO - [2022-11-18 07:14:24,610] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from airflow_multi_dagrun.operators import TriggerMultiDagRunOperator
ModuleNotFoundError: No module named 'airflow_multi_dagrun'
[2022-11-18 07:14:24,673] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-18 07:14:24,709] {processor.py:171} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.511 seconds
[2022-11-18 07:14:56,142] {processor.py:163} INFO - Started process (PID=2271) to work on /opt/airflow/dags/queue_reader.py
[2022-11-18 07:14:56,148] {processor.py:642} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-18 07:14:56,152] {logging_mixin.py:109} INFO - [2022-11-18 07:14:56,152] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-18 07:14:56,488] {logging_mixin.py:109} INFO - [2022-11-18 07:14:56,479] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from airflow_multi_dagrun.operators import TriggerMultiDagRunOperator
ModuleNotFoundError: No module named 'airflow_multi_dagrun'
[2022-11-18 07:14:56,542] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-18 07:14:56,561] {processor.py:171} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.427 seconds
[2022-11-18 07:15:27,434] {processor.py:163} INFO - Started process (PID=2323) to work on /opt/airflow/dags/queue_reader.py
[2022-11-18 07:15:27,436] {processor.py:642} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-18 07:15:27,437] {logging_mixin.py:109} INFO - [2022-11-18 07:15:27,437] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-18 07:15:27,593] {logging_mixin.py:109} INFO - [2022-11-18 07:15:27,591] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from airflow_multi_dagrun.operators import TriggerMultiDagRunOperator
ModuleNotFoundError: No module named 'airflow_multi_dagrun'
[2022-11-18 07:15:27,612] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-18 07:15:27,623] {processor.py:171} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.193 seconds
[2022-11-18 07:16:01,656] {processor.py:163} INFO - Started process (PID=2370) to work on /opt/airflow/dags/queue_reader.py
[2022-11-18 07:16:01,674] {processor.py:642} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-18 07:16:01,675] {logging_mixin.py:109} INFO - [2022-11-18 07:16:01,675] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-18 07:16:02,476] {logging_mixin.py:109} INFO - [2022-11-18 07:16:02,447] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from airflow_multi_dagrun.operators import TriggerMultiDagRunOperator
ModuleNotFoundError: No module named 'airflow_multi_dagrun'
[2022-11-18 07:16:02,742] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-18 07:16:02,861] {processor.py:171} INFO - Processing /opt/airflow/dags/queue_reader.py took 1.240 seconds
[2022-11-18 07:17:15,898] {processor.py:163} INFO - Started process (PID=2428) to work on /opt/airflow/dags/queue_reader.py
[2022-11-18 07:17:15,924] {processor.py:642} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-18 07:17:15,945] {logging_mixin.py:109} INFO - [2022-11-18 07:17:15,944] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-18 07:17:20,902] {logging_mixin.py:109} INFO - [2022-11-18 07:17:20,719] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from airflow_multi_dagrun.operators import TriggerMultiDagRunOperator
ModuleNotFoundError: No module named 'airflow_multi_dagrun'
[2022-11-18 07:17:22,355] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-18 07:17:23,272] {processor.py:171} INFO - Processing /opt/airflow/dags/queue_reader.py took 7.409 seconds
[2022-11-18 11:03:17,543] {processor.py:163} INFO - Started process (PID=47) to work on /opt/airflow/dags/queue_reader.py
[2022-11-18 11:03:17,553] {processor.py:642} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-18 11:03:17,579] {logging_mixin.py:109} INFO - [2022-11-18 11:03:17,579] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-18 11:03:19,783] {logging_mixin.py:109} INFO - [2022-11-18 11:03:19,776] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from airflow_multi_dagrun.operators import TriggerMultiDagRunOperator
ModuleNotFoundError: No module named 'airflow_multi_dagrun'
[2022-11-18 11:03:19,929] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-18 11:03:19,974] {processor.py:171} INFO - Processing /opt/airflow/dags/queue_reader.py took 2.480 seconds
[2022-11-18 11:11:16,264] {processor.py:163} INFO - Started process (PID=45) to work on /opt/airflow/dags/queue_reader.py
[2022-11-18 11:11:16,277] {processor.py:642} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-18 11:11:16,278] {logging_mixin.py:109} INFO - [2022-11-18 11:11:16,278] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-18 11:11:18,173] {logging_mixin.py:109} INFO - [2022-11-18 11:11:18,151] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from airflow_multi_dagrun.operators import TriggerMultiDagRunOperator
ModuleNotFoundError: No module named 'airflow_multi_dagrun'
[2022-11-18 11:11:18,259] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-18 11:11:18,305] {processor.py:171} INFO - Processing /opt/airflow/dags/queue_reader.py took 2.057 seconds
[2022-11-18 11:13:30,448] {processor.py:163} INFO - Started process (PID=196) to work on /opt/airflow/dags/queue_reader.py
[2022-11-18 11:13:30,450] {processor.py:642} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-18 11:13:30,451] {logging_mixin.py:109} INFO - [2022-11-18 11:13:30,451] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-18 11:13:30,620] {logging_mixin.py:109} INFO - [2022-11-18 11:13:30,613] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from airflow_multi_dagrun.operators import TriggerMultiDagRunOperator
ModuleNotFoundError: No module named 'airflow_multi_dagrun'
[2022-11-18 11:13:30,647] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-18 11:13:30,659] {processor.py:171} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.215 seconds
[2022-11-18 11:14:01,395] {processor.py:163} INFO - Started process (PID=248) to work on /opt/airflow/dags/queue_reader.py
[2022-11-18 11:14:01,397] {processor.py:642} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-18 11:14:01,398] {logging_mixin.py:109} INFO - [2022-11-18 11:14:01,397] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-18 11:14:01,565] {logging_mixin.py:109} INFO - [2022-11-18 11:14:01,564] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from airflow_multi_dagrun.operators import TriggerMultiDagRunOperator
ModuleNotFoundError: No module named 'airflow_multi_dagrun'
[2022-11-18 11:14:01,598] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-18 11:14:01,613] {processor.py:171} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.223 seconds
[2022-11-18 11:14:31,717] {processor.py:163} INFO - Started process (PID=301) to work on /opt/airflow/dags/queue_reader.py
[2022-11-18 11:14:31,723] {processor.py:642} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-18 11:14:31,727] {logging_mixin.py:109} INFO - [2022-11-18 11:14:31,727] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-18 11:14:31,996] {logging_mixin.py:109} INFO - [2022-11-18 11:14:31,992] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from airflow_multi_dagrun.operators import TriggerMultiDagRunOperator
ModuleNotFoundError: No module named 'airflow_multi_dagrun'
[2022-11-18 11:14:32,034] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-18 11:14:32,055] {processor.py:171} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.361 seconds
[2022-11-18 11:15:02,235] {processor.py:163} INFO - Started process (PID=361) to work on /opt/airflow/dags/queue_reader.py
[2022-11-18 11:15:02,237] {processor.py:642} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-18 11:15:02,240] {logging_mixin.py:109} INFO - [2022-11-18 11:15:02,239] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-18 11:15:02,903] {logging_mixin.py:109} INFO - [2022-11-18 11:15:02,887] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from airflow_multi_dagrun.operators import TriggerMultiDagRunOperator
ModuleNotFoundError: No module named 'airflow_multi_dagrun'
[2022-11-18 11:15:02,951] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-18 11:15:02,991] {processor.py:171} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.765 seconds
[2022-11-18 11:15:33,348] {processor.py:163} INFO - Started process (PID=416) to work on /opt/airflow/dags/queue_reader.py
[2022-11-18 11:15:33,351] {processor.py:642} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-18 11:15:33,352] {logging_mixin.py:109} INFO - [2022-11-18 11:15:33,352] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-18 11:15:33,548] {logging_mixin.py:109} INFO - [2022-11-18 11:15:33,547] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from airflow_multi_dagrun.operators import TriggerMultiDagRunOperator
ModuleNotFoundError: No module named 'airflow_multi_dagrun'
[2022-11-18 11:15:33,580] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-18 11:15:33,602] {processor.py:171} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.258 seconds
[2022-11-18 11:16:03,837] {processor.py:163} INFO - Started process (PID=460) to work on /opt/airflow/dags/queue_reader.py
[2022-11-18 11:16:03,839] {processor.py:642} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-18 11:16:03,840] {logging_mixin.py:109} INFO - [2022-11-18 11:16:03,840] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-18 11:16:04,000] {logging_mixin.py:109} INFO - [2022-11-18 11:16:03,998] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from airflow_multi_dagrun.operators import TriggerMultiDagRunOperator
ModuleNotFoundError: No module named 'airflow_multi_dagrun'
[2022-11-18 11:16:04,023] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-18 11:16:04,034] {processor.py:171} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.203 seconds
[2022-11-18 11:16:34,104] {processor.py:163} INFO - Started process (PID=514) to work on /opt/airflow/dags/queue_reader.py
[2022-11-18 11:16:34,109] {processor.py:642} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-18 11:16:34,120] {logging_mixin.py:109} INFO - [2022-11-18 11:16:34,119] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-18 11:16:34,495] {logging_mixin.py:109} INFO - [2022-11-18 11:16:34,494] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from airflow_multi_dagrun.operators import TriggerMultiDagRunOperator
ModuleNotFoundError: No module named 'airflow_multi_dagrun'
[2022-11-18 11:16:34,524] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-18 11:16:34,543] {processor.py:171} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.451 seconds
[2022-11-18 11:17:04,974] {processor.py:163} INFO - Started process (PID=566) to work on /opt/airflow/dags/queue_reader.py
[2022-11-18 11:17:04,988] {processor.py:642} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-18 11:17:04,990] {logging_mixin.py:109} INFO - [2022-11-18 11:17:04,990] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-18 11:17:05,354] {logging_mixin.py:109} INFO - [2022-11-18 11:17:05,353] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from airflow_multi_dagrun.operators import TriggerMultiDagRunOperator
ModuleNotFoundError: No module named 'airflow_multi_dagrun'
[2022-11-18 11:17:05,379] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-18 11:17:05,391] {processor.py:171} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.428 seconds
[2022-11-18 11:17:35,596] {processor.py:163} INFO - Started process (PID=618) to work on /opt/airflow/dags/queue_reader.py
[2022-11-18 11:17:35,602] {processor.py:642} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-18 11:17:35,609] {logging_mixin.py:109} INFO - [2022-11-18 11:17:35,608] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-18 11:17:36,015] {logging_mixin.py:109} INFO - [2022-11-18 11:17:36,014] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from airflow_multi_dagrun.operators import TriggerMultiDagRunOperator
ModuleNotFoundError: No module named 'airflow_multi_dagrun'
[2022-11-18 11:17:36,035] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-18 11:17:36,058] {processor.py:171} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.473 seconds
[2022-11-18 11:18:06,337] {processor.py:163} INFO - Started process (PID=671) to work on /opt/airflow/dags/queue_reader.py
[2022-11-18 11:18:06,340] {processor.py:642} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-18 11:18:06,342] {logging_mixin.py:109} INFO - [2022-11-18 11:18:06,341] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-18 11:18:06,550] {logging_mixin.py:109} INFO - [2022-11-18 11:18:06,549] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from airflow_multi_dagrun.operators import TriggerMultiDagRunOperator
ModuleNotFoundError: No module named 'airflow_multi_dagrun'
[2022-11-18 11:18:06,571] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-18 11:18:06,589] {processor.py:171} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.261 seconds
[2022-11-18 11:18:37,520] {processor.py:163} INFO - Started process (PID=725) to work on /opt/airflow/dags/queue_reader.py
[2022-11-18 11:18:37,523] {processor.py:642} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-18 11:18:37,524] {logging_mixin.py:109} INFO - [2022-11-18 11:18:37,524] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-18 11:18:37,719] {logging_mixin.py:109} INFO - [2022-11-18 11:18:37,718] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from airflow_multi_dagrun.operators import TriggerMultiDagRunOperator
ModuleNotFoundError: No module named 'airflow_multi_dagrun'
[2022-11-18 11:18:37,739] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-18 11:18:37,751] {processor.py:171} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.236 seconds
[2022-11-18 11:19:07,816] {processor.py:163} INFO - Started process (PID=779) to work on /opt/airflow/dags/queue_reader.py
[2022-11-18 11:19:07,817] {processor.py:642} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-18 11:19:07,818] {logging_mixin.py:109} INFO - [2022-11-18 11:19:07,818] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-18 11:19:07,988] {logging_mixin.py:109} INFO - [2022-11-18 11:19:07,986] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from airflow_multi_dagrun.operators import TriggerMultiDagRunOperator
ModuleNotFoundError: No module named 'airflow_multi_dagrun'
[2022-11-18 11:19:08,006] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-18 11:19:08,018] {processor.py:171} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.207 seconds
[2022-11-18 11:19:38,510] {processor.py:163} INFO - Started process (PID=837) to work on /opt/airflow/dags/queue_reader.py
[2022-11-18 11:19:38,532] {processor.py:642} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-18 11:19:38,539] {logging_mixin.py:109} INFO - [2022-11-18 11:19:38,539] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-18 11:19:39,613] {logging_mixin.py:109} INFO - [2022-11-18 11:19:39,611] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from airflow_multi_dagrun.operators import TriggerMultiDagRunOperator
ModuleNotFoundError: No module named 'airflow_multi_dagrun'
[2022-11-18 11:19:39,706] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-18 11:19:39,799] {processor.py:171} INFO - Processing /opt/airflow/dags/queue_reader.py took 1.308 seconds
[2022-11-18 11:20:10,648] {processor.py:163} INFO - Started process (PID=892) to work on /opt/airflow/dags/queue_reader.py
[2022-11-18 11:20:10,655] {processor.py:642} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-18 11:20:10,661] {logging_mixin.py:109} INFO - [2022-11-18 11:20:10,661] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-18 11:20:11,335] {logging_mixin.py:109} INFO - [2022-11-18 11:20:11,329] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from airflow_multi_dagrun.operators import TriggerMultiDagRunOperator
ModuleNotFoundError: No module named 'airflow_multi_dagrun'
[2022-11-18 11:20:11,384] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-18 11:20:11,403] {processor.py:171} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.760 seconds
[2022-11-18 11:20:41,960] {processor.py:163} INFO - Started process (PID=945) to work on /opt/airflow/dags/queue_reader.py
[2022-11-18 11:20:41,962] {processor.py:642} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-18 11:20:41,972] {logging_mixin.py:109} INFO - [2022-11-18 11:20:41,971] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-18 11:20:42,523] {logging_mixin.py:109} INFO - [2022-11-18 11:20:42,519] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from airflow_multi_dagrun.operators import TriggerMultiDagRunOperator
ModuleNotFoundError: No module named 'airflow_multi_dagrun'
[2022-11-18 11:20:42,585] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-18 11:20:42,629] {processor.py:171} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.686 seconds
[2022-11-18 11:21:13,046] {processor.py:163} INFO - Started process (PID=1002) to work on /opt/airflow/dags/queue_reader.py
[2022-11-18 11:21:13,053] {processor.py:642} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-18 11:21:13,061] {logging_mixin.py:109} INFO - [2022-11-18 11:21:13,061] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-18 11:21:13,525] {logging_mixin.py:109} INFO - [2022-11-18 11:21:13,519] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from airflow_multi_dagrun.operators import TriggerMultiDagRunOperator
ModuleNotFoundError: No module named 'airflow_multi_dagrun'
[2022-11-18 11:21:13,567] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-18 11:21:13,594] {processor.py:171} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.553 seconds
[2022-11-18 11:21:44,412] {processor.py:163} INFO - Started process (PID=1053) to work on /opt/airflow/dags/queue_reader.py
[2022-11-18 11:21:44,420] {processor.py:642} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-18 11:21:44,421] {logging_mixin.py:109} INFO - [2022-11-18 11:21:44,421] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-18 11:21:44,593] {logging_mixin.py:109} INFO - [2022-11-18 11:21:44,592] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from airflow_multi_dagrun.operators import TriggerMultiDagRunOperator
ModuleNotFoundError: No module named 'airflow_multi_dagrun'
[2022-11-18 11:21:44,614] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-18 11:21:44,632] {processor.py:171} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.225 seconds
[2022-11-18 11:23:10,989] {processor.py:163} INFO - Started process (PID=38) to work on /opt/airflow/dags/queue_reader.py
[2022-11-18 11:23:10,991] {processor.py:642} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-18 11:23:11,000] {logging_mixin.py:109} INFO - [2022-11-18 11:23:11,000] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-18 11:23:11,388] {logging_mixin.py:109} INFO - [2022-11-18 11:23:11,382] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from airflow_multi_dagrun.operators import TriggerMultiDagRunOperator
ModuleNotFoundError: No module named 'airflow_multi_dagrun'
[2022-11-18 11:23:11,436] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-18 11:23:11,465] {processor.py:171} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.494 seconds
[2022-11-18 11:23:42,044] {processor.py:163} INFO - Started process (PID=90) to work on /opt/airflow/dags/queue_reader.py
[2022-11-18 11:23:42,045] {processor.py:642} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-18 11:23:42,046] {logging_mixin.py:109} INFO - [2022-11-18 11:23:42,046] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-18 11:23:42,135] {logging_mixin.py:109} INFO - [2022-11-18 11:23:42,135] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from airflow_multi_dagrun.operators import TriggerMultiDagRunOperator
ModuleNotFoundError: No module named 'airflow_multi_dagrun'
[2022-11-18 11:23:42,152] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-18 11:23:42,161] {processor.py:171} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.122 seconds
[2022-11-18 11:24:13,027] {processor.py:163} INFO - Started process (PID=143) to work on /opt/airflow/dags/queue_reader.py
[2022-11-18 11:24:13,029] {processor.py:642} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-18 11:24:13,031] {logging_mixin.py:109} INFO - [2022-11-18 11:24:13,031] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-18 11:24:13,224] {logging_mixin.py:109} INFO - [2022-11-18 11:24:13,220] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from airflow_multi_dagrun.operators import TriggerMultiDagRunOperator
ModuleNotFoundError: No module named 'airflow_multi_dagrun'
[2022-11-18 11:24:13,260] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-18 11:24:13,286] {processor.py:171} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.263 seconds
[2022-11-18 11:24:43,662] {processor.py:163} INFO - Started process (PID=197) to work on /opt/airflow/dags/queue_reader.py
[2022-11-18 11:24:43,667] {processor.py:642} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-18 11:24:43,673] {logging_mixin.py:109} INFO - [2022-11-18 11:24:43,673] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-18 11:24:44,048] {logging_mixin.py:109} INFO - [2022-11-18 11:24:44,040] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from airflow_multi_dagrun.operators import TriggerMultiDagRunOperator
ModuleNotFoundError: No module named 'airflow_multi_dagrun'
[2022-11-18 11:24:44,088] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-18 11:24:44,115] {processor.py:171} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.483 seconds
[2022-11-18 11:25:14,294] {processor.py:163} INFO - Started process (PID=250) to work on /opt/airflow/dags/queue_reader.py
[2022-11-18 11:25:14,295] {processor.py:642} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-18 11:25:14,296] {logging_mixin.py:109} INFO - [2022-11-18 11:25:14,296] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-18 11:25:14,418] {logging_mixin.py:109} INFO - [2022-11-18 11:25:14,416] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from airflow_multi_dagrun.operators import TriggerMultiDagRunOperator
ModuleNotFoundError: No module named 'airflow_multi_dagrun'
[2022-11-18 11:25:14,434] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-18 11:25:14,444] {processor.py:171} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.154 seconds
[2022-11-18 11:25:44,964] {processor.py:163} INFO - Started process (PID=303) to work on /opt/airflow/dags/queue_reader.py
[2022-11-18 11:25:44,965] {processor.py:642} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-18 11:25:44,966] {logging_mixin.py:109} INFO - [2022-11-18 11:25:44,966] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-18 11:25:45,056] {logging_mixin.py:109} INFO - [2022-11-18 11:25:45,055] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from airflow_multi_dagrun.operators import TriggerMultiDagRunOperator
ModuleNotFoundError: No module named 'airflow_multi_dagrun'
[2022-11-18 11:25:45,072] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-18 11:25:45,085] {processor.py:171} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.125 seconds
[2022-11-18 11:26:15,155] {processor.py:163} INFO - Started process (PID=355) to work on /opt/airflow/dags/queue_reader.py
[2022-11-18 11:26:15,158] {processor.py:642} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-18 11:26:15,159] {logging_mixin.py:109} INFO - [2022-11-18 11:26:15,159] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-18 11:26:15,301] {logging_mixin.py:109} INFO - [2022-11-18 11:26:15,300] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from airflow_multi_dagrun.operators import TriggerMultiDagRunOperator
ModuleNotFoundError: No module named 'airflow_multi_dagrun'
[2022-11-18 11:26:15,327] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-18 11:26:15,345] {processor.py:171} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.197 seconds
[2022-11-18 11:26:45,835] {processor.py:163} INFO - Started process (PID=409) to work on /opt/airflow/dags/queue_reader.py
[2022-11-18 11:26:45,838] {processor.py:642} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-18 11:26:45,841] {logging_mixin.py:109} INFO - [2022-11-18 11:26:45,841] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-18 11:26:46,041] {logging_mixin.py:109} INFO - [2022-11-18 11:26:46,034] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from airflow_multi_dagrun.operators import TriggerMultiDagRunOperator
ModuleNotFoundError: No module named 'airflow_multi_dagrun'
[2022-11-18 11:26:46,065] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-18 11:26:46,074] {processor.py:171} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.244 seconds
[2022-11-18 11:27:16,542] {processor.py:163} INFO - Started process (PID=460) to work on /opt/airflow/dags/queue_reader.py
[2022-11-18 11:27:16,544] {processor.py:642} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-18 11:27:16,546] {logging_mixin.py:109} INFO - [2022-11-18 11:27:16,545] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-18 11:27:16,634] {logging_mixin.py:109} INFO - [2022-11-18 11:27:16,633] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from airflow_multi_dagrun.operators import TriggerMultiDagRunOperator
ModuleNotFoundError: No module named 'airflow_multi_dagrun'
[2022-11-18 11:27:16,651] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-18 11:27:16,663] {processor.py:171} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.129 seconds
[2022-11-18 11:27:46,759] {processor.py:163} INFO - Started process (PID=512) to work on /opt/airflow/dags/queue_reader.py
[2022-11-18 11:27:46,769] {processor.py:642} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-18 11:27:46,772] {logging_mixin.py:109} INFO - [2022-11-18 11:27:46,772] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-18 11:27:47,023] {logging_mixin.py:109} INFO - [2022-11-18 11:27:47,016] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from airflow_multi_dagrun.operators import TriggerMultiDagRunOperator
ModuleNotFoundError: No module named 'airflow_multi_dagrun'
[2022-11-18 11:27:47,048] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-18 11:27:47,064] {processor.py:171} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.310 seconds
[2022-11-18 11:28:17,136] {processor.py:163} INFO - Started process (PID=564) to work on /opt/airflow/dags/queue_reader.py
[2022-11-18 11:28:17,139] {processor.py:642} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-18 11:28:17,140] {logging_mixin.py:109} INFO - [2022-11-18 11:28:17,140] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-18 11:28:17,300] {logging_mixin.py:109} INFO - [2022-11-18 11:28:17,299] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from airflow_multi_dagrun.operators import TriggerMultiDagRunOperator
ModuleNotFoundError: No module named 'airflow_multi_dagrun'
[2022-11-18 11:28:17,322] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-18 11:28:17,336] {processor.py:171} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.205 seconds
[2022-11-18 11:28:47,484] {processor.py:163} INFO - Started process (PID=618) to work on /opt/airflow/dags/queue_reader.py
[2022-11-18 11:28:47,487] {processor.py:642} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-18 11:28:47,488] {logging_mixin.py:109} INFO - [2022-11-18 11:28:47,488] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-18 11:28:47,670] {logging_mixin.py:109} INFO - [2022-11-18 11:28:47,659] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from airflow_multi_dagrun.operators import TriggerMultiDagRunOperator
ModuleNotFoundError: No module named 'airflow_multi_dagrun'
[2022-11-18 11:28:47,695] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-18 11:28:47,716] {processor.py:171} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.240 seconds
[2022-11-18 11:29:06,706] {processor.py:163} INFO - Started process (PID=651) to work on /opt/airflow/dags/queue_reader.py
[2022-11-18 11:29:06,718] {processor.py:642} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-18 11:29:06,725] {logging_mixin.py:109} INFO - [2022-11-18 11:29:06,725] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-18 11:29:07,990] {logging_mixin.py:109} INFO - [2022-11-18 11:29:07,980] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from omniParser.omniparser.parser import OmniParser
  File "/opt/airflow/dags/omniParser/omniparser/parser.py", line 6, in <module>
    from smart_open import open
ModuleNotFoundError: No module named 'smart_open'
[2022-11-18 11:29:08,296] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-18 11:29:08,337] {processor.py:171} INFO - Processing /opt/airflow/dags/queue_reader.py took 1.656 seconds
[2022-11-18 11:29:38,676] {processor.py:163} INFO - Started process (PID=705) to work on /opt/airflow/dags/queue_reader.py
[2022-11-18 11:29:38,678] {processor.py:642} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-18 11:29:38,679] {logging_mixin.py:109} INFO - [2022-11-18 11:29:38,679] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-18 11:29:38,924] {logging_mixin.py:109} INFO - [2022-11-18 11:29:38,921] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from omniParser.omniparser.parser import OmniParser
  File "/opt/airflow/dags/omniParser/omniparser/parser.py", line 6, in <module>
    from smart_open import open
ModuleNotFoundError: No module named 'smart_open'
[2022-11-18 11:29:39,051] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-18 11:29:39,108] {processor.py:171} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.446 seconds
[2022-11-18 11:30:09,252] {processor.py:163} INFO - Started process (PID=757) to work on /opt/airflow/dags/queue_reader.py
[2022-11-18 11:30:09,254] {processor.py:642} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-18 11:30:09,255] {logging_mixin.py:109} INFO - [2022-11-18 11:30:09,254] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-18 11:30:09,387] {logging_mixin.py:109} INFO - [2022-11-18 11:30:09,385] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from omniParser.omniparser.parser import OmniParser
  File "/opt/airflow/dags/omniParser/omniparser/parser.py", line 6, in <module>
    from smart_open import open
ModuleNotFoundError: No module named 'smart_open'
[2022-11-18 11:30:09,412] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-18 11:30:09,428] {processor.py:171} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.181 seconds
[2022-11-18 11:30:39,966] {processor.py:163} INFO - Started process (PID=809) to work on /opt/airflow/dags/queue_reader.py
[2022-11-18 11:30:39,971] {processor.py:642} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-18 11:30:39,972] {logging_mixin.py:109} INFO - [2022-11-18 11:30:39,972] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-18 11:30:40,299] {logging_mixin.py:109} INFO - [2022-11-18 11:30:40,298] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from omniParser.omniparser.parser import OmniParser
  File "/opt/airflow/dags/omniParser/omniparser/parser.py", line 6, in <module>
    from smart_open import open
ModuleNotFoundError: No module named 'smart_open'
[2022-11-18 11:30:40,321] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-18 11:30:40,336] {processor.py:171} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.379 seconds
[2022-11-18 11:30:46,368] {processor.py:163} INFO - Started process (PID=816) to work on /opt/airflow/dags/queue_reader.py
[2022-11-18 11:30:46,372] {processor.py:642} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-18 11:30:46,373] {logging_mixin.py:109} INFO - [2022-11-18 11:30:46,373] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-18 11:30:46,584] {logging_mixin.py:109} INFO - [2022-11-18 11:30:46,582] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from airflow_omniparser.dags.omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'airflow_omniparser'
[2022-11-18 11:30:46,619] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-18 11:30:46,643] {processor.py:171} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.283 seconds
[2022-11-18 11:31:16,724] {processor.py:163} INFO - Started process (PID=868) to work on /opt/airflow/dags/queue_reader.py
[2022-11-18 11:31:16,726] {processor.py:642} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-18 11:31:16,727] {logging_mixin.py:109} INFO - [2022-11-18 11:31:16,727] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-18 11:31:16,881] {logging_mixin.py:109} INFO - [2022-11-18 11:31:16,880] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from airflow_omniparser.dags.omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'airflow_omniparser'
[2022-11-18 11:31:16,905] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-18 11:31:16,920] {processor.py:171} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.202 seconds
[2022-11-18 11:31:47,105] {processor.py:163} INFO - Started process (PID=921) to work on /opt/airflow/dags/queue_reader.py
[2022-11-18 11:31:47,107] {processor.py:642} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-18 11:31:47,108] {logging_mixin.py:109} INFO - [2022-11-18 11:31:47,108] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-18 11:31:47,311] {logging_mixin.py:109} INFO - [2022-11-18 11:31:47,309] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from airflow_omniparser.dags.omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'airflow_omniparser'
[2022-11-18 11:31:47,335] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-18 11:31:47,348] {processor.py:171} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.249 seconds
[2022-11-18 11:32:17,568] {processor.py:163} INFO - Started process (PID=971) to work on /opt/airflow/dags/queue_reader.py
[2022-11-18 11:32:17,580] {processor.py:642} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-18 11:32:17,586] {logging_mixin.py:109} INFO - [2022-11-18 11:32:17,586] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-18 11:32:18,445] {logging_mixin.py:109} INFO - [2022-11-18 11:32:18,431] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from airflow_omniparser.dags.omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'airflow_omniparser'
[2022-11-18 11:32:18,512] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-18 11:32:18,579] {processor.py:171} INFO - Processing /opt/airflow/dags/queue_reader.py took 1.033 seconds
[2022-11-18 11:32:48,681] {processor.py:163} INFO - Started process (PID=1018) to work on /opt/airflow/dags/queue_reader.py
[2022-11-18 11:32:48,683] {processor.py:642} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-18 11:32:48,684] {logging_mixin.py:109} INFO - [2022-11-18 11:32:48,684] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-18 11:32:48,840] {logging_mixin.py:109} INFO - [2022-11-18 11:32:48,839] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from airflow_omniparser.dags.omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'airflow_omniparser'
[2022-11-18 11:32:48,885] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-18 11:32:48,910] {processor.py:171} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.235 seconds
[2022-11-18 11:33:55,346] {processor.py:163} INFO - Started process (PID=1087) to work on /opt/airflow/dags/queue_reader.py
[2022-11-18 11:33:55,389] {processor.py:642} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-18 11:33:55,414] {logging_mixin.py:109} INFO - [2022-11-18 11:33:55,414] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-18 11:34:00,569] {logging_mixin.py:109} INFO - [2022-11-18 11:34:00,532] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from airflow_omniparser.dags.omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'airflow_omniparser'
[2022-11-18 11:34:00,865] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-18 11:34:01,197] {processor.py:171} INFO - Processing /opt/airflow/dags/queue_reader.py took 5.889 seconds
[2022-11-18 11:39:20,972] {processor.py:163} INFO - Started process (PID=1224) to work on /opt/airflow/dags/queue_reader.py
[2022-11-18 11:39:21,485] {processor.py:642} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-18 11:39:22,162] {logging_mixin.py:109} INFO - [2022-11-18 11:39:21,957] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-18 11:39:55,807] {logging_mixin.py:109} INFO - [2022-11-18 11:39:55,434] {timeout.py:36} ERROR - Process timed out, PID: 1224
[2022-11-18 11:40:14,726] {logging_mixin.py:109} INFO - [2022-11-18 11:40:11,158] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 857, in get_code
  File "<frozen importlib._bootstrap_external>", line 525, in _compile_bytecode
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/dag_processing/manager.py", line 496, in _exit_gracefully
    self.log.debug("Current Stacktrace is: %s", '\n'.join(map(str, inspect.stack())))
  File "/usr/local/lib/python3.7/inspect.py", line 1513, in stack
    return getouterframes(sys._getframe(1), context)
  File "/usr/local/lib/python3.7/inspect.py", line 1490, in getouterframes
    frameinfo = (frame,) + getframeinfo(frame, context)
  File "/usr/local/lib/python3.7/inspect.py", line 1464, in getframeinfo
    lines, lnum = findsource(frame)
  File "/usr/local/lib/python3.7/inspect.py", line 780, in findsource
    module = getmodule(object, file)
  File "/usr/local/lib/python3.7/inspect.py", line 739, in getmodule
    f = getabsfile(module)
  File "/usr/local/lib/python3.7/inspect.py", line 708, in getabsfile
    _filename = getsourcefile(object) or getfile(object)
  File "/usr/local/lib/python3.7/inspect.py", line 693, in getsourcefile
    if os.path.exists(filename):
  File "/usr/local/lib/python3.7/genericpath.py", line 19, in exists
    os.stat(path)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 37, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/queue_reader.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.2.4/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.2.4/best-practices.html#reducing-dag-complexity, PID: 1224
[2022-11-18 11:50:39,870] {processor.py:163} INFO - Started process (PID=1338) to work on /opt/airflow/dags/queue_reader.py
[2022-11-18 11:50:42,720] {processor.py:642} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-18 11:50:45,312] {logging_mixin.py:109} INFO - [2022-11-18 11:50:44,160] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-18 11:51:37,312] {logging_mixin.py:109} INFO - [2022-11-18 11:51:35,635] {timeout.py:36} ERROR - Process timed out, PID: 1338
[2022-11-18 11:52:43,792] {logging_mixin.py:109} INFO - [2022-11-18 11:52:17,627] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "<frozen importlib._bootstrap_external>", line 87, in _path_is_mode_type
  File "<frozen importlib._bootstrap_external>", line 81, in _path_stat
FileNotFoundError: [Errno 2] No such file or directory: '/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/__init__.py'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 3, in <module>
    from airflow.providers.amazon.aws.sensors.sqs import SqsSensor
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 963, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 906, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1280, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1252, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1383, in find_spec
  File "<frozen importlib._bootstrap_external>", line 95, in _path_isfile
  File "<frozen importlib._bootstrap_external>", line 87, in _path_is_mode_type
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 37, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/queue_reader.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.2.4/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.2.4/best-practices.html#reducing-dag-complexity, PID: 1338
[2022-11-18 12:06:53,925] {processor.py:163} INFO - Started process (PID=63) to work on /opt/airflow/dags/queue_reader.py
[2022-11-18 12:06:53,946] {processor.py:642} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-18 12:06:53,955] {logging_mixin.py:109} INFO - [2022-11-18 12:06:53,955] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-18 12:06:55,613] {logging_mixin.py:109} INFO - [2022-11-18 12:06:55,592] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from airflow_omniparser.dags.omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'airflow_omniparser'
[2022-11-18 12:06:55,702] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-18 12:06:55,767] {processor.py:171} INFO - Processing /opt/airflow/dags/queue_reader.py took 1.872 seconds
[2022-11-18 12:07:30,727] {processor.py:163} INFO - Started process (PID=109) to work on /opt/airflow/dags/queue_reader.py
[2022-11-18 12:07:30,744] {processor.py:642} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-18 12:07:30,765] {logging_mixin.py:109} INFO - [2022-11-18 12:07:30,765] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-18 12:07:32,830] {logging_mixin.py:109} INFO - [2022-11-18 12:07:32,791] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from airflow_omniparser.dags.omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'airflow_omniparser'
[2022-11-18 12:07:33,064] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-18 12:07:33,173] {processor.py:171} INFO - Processing /opt/airflow/dags/queue_reader.py took 2.531 seconds
[2022-11-18 12:08:03,442] {processor.py:163} INFO - Started process (PID=161) to work on /opt/airflow/dags/queue_reader.py
[2022-11-18 12:08:03,444] {processor.py:642} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-18 12:08:03,445] {logging_mixin.py:109} INFO - [2022-11-18 12:08:03,445] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-18 12:08:03,611] {logging_mixin.py:109} INFO - [2022-11-18 12:08:03,609] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from airflow_omniparser.dags.omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'airflow_omniparser'
[2022-11-18 12:08:03,670] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-18 12:08:03,696] {processor.py:171} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.260 seconds
[2022-11-18 12:08:33,908] {processor.py:163} INFO - Started process (PID=214) to work on /opt/airflow/dags/queue_reader.py
[2022-11-18 12:08:33,914] {processor.py:642} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-18 12:08:33,915] {logging_mixin.py:109} INFO - [2022-11-18 12:08:33,915] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-18 12:08:34,054] {logging_mixin.py:109} INFO - [2022-11-18 12:08:34,052] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from airflow_omniparser.dags.omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'airflow_omniparser'
[2022-11-18 12:08:34,101] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-18 12:08:34,119] {processor.py:171} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.216 seconds
[2022-11-18 12:09:04,238] {processor.py:163} INFO - Started process (PID=267) to work on /opt/airflow/dags/queue_reader.py
[2022-11-18 12:09:04,241] {processor.py:642} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-18 12:09:04,249] {logging_mixin.py:109} INFO - [2022-11-18 12:09:04,248] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-18 12:09:04,606] {logging_mixin.py:109} INFO - [2022-11-18 12:09:04,603] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from airflow_omniparser.dags.omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'airflow_omniparser'
[2022-11-18 12:09:04,650] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-18 12:09:04,686] {processor.py:171} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.477 seconds
[2022-11-18 12:09:35,011] {processor.py:163} INFO - Started process (PID=319) to work on /opt/airflow/dags/queue_reader.py
[2022-11-18 12:09:35,014] {processor.py:642} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-18 12:09:35,015] {logging_mixin.py:109} INFO - [2022-11-18 12:09:35,015] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-18 12:09:35,359] {logging_mixin.py:109} INFO - [2022-11-18 12:09:35,357] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from airflow_omniparser.dags.omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'airflow_omniparser'
[2022-11-18 12:09:35,452] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-18 12:09:35,481] {processor.py:171} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.477 seconds
[2022-11-18 12:10:06,280] {processor.py:163} INFO - Started process (PID=371) to work on /opt/airflow/dags/queue_reader.py
[2022-11-18 12:10:06,283] {processor.py:642} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-18 12:10:06,291] {logging_mixin.py:109} INFO - [2022-11-18 12:10:06,291] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-18 12:10:06,703] {logging_mixin.py:109} INFO - [2022-11-18 12:10:06,701] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from airflow_omniparser.dags.omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'airflow_omniparser'
[2022-11-18 12:10:06,732] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-18 12:10:06,749] {processor.py:171} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.474 seconds
[2022-11-18 12:10:37,061] {processor.py:163} INFO - Started process (PID=424) to work on /opt/airflow/dags/queue_reader.py
[2022-11-18 12:10:37,076] {processor.py:642} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-18 12:10:37,085] {logging_mixin.py:109} INFO - [2022-11-18 12:10:37,084] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-18 12:10:38,096] {logging_mixin.py:109} INFO - [2022-11-18 12:10:38,084] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from airflow_omniparser.dags.omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'airflow_omniparser'
[2022-11-18 12:10:38,184] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-18 12:10:38,237] {processor.py:171} INFO - Processing /opt/airflow/dags/queue_reader.py took 1.218 seconds
[2022-11-18 12:11:08,437] {processor.py:163} INFO - Started process (PID=471) to work on /opt/airflow/dags/queue_reader.py
[2022-11-18 12:11:08,451] {processor.py:642} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-18 12:11:08,457] {logging_mixin.py:109} INFO - [2022-11-18 12:11:08,456] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-18 12:11:08,950] {logging_mixin.py:109} INFO - [2022-11-18 12:11:08,942] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from airflow_omniparser.dags.omniParser.omniparser.parser import OmniParser
ModuleNotFoundError: No module named 'airflow_omniparser'
[2022-11-18 12:11:08,992] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-18 12:11:09,028] {processor.py:171} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.608 seconds
[2022-11-18 12:11:21,461] {processor.py:163} INFO - Started process (PID=491) to work on /opt/airflow/dags/queue_reader.py
[2022-11-18 12:11:21,464] {processor.py:642} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-18 12:11:21,465] {logging_mixin.py:109} INFO - [2022-11-18 12:11:21,465] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-18 12:11:21,557] {logging_mixin.py:109} INFO - [2022-11-18 12:11:21,556] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from omniParser.omniparser.parser import OmniParser
  File "/opt/airflow/dags/omniParser/omniparser/parser.py", line 6, in <module>
    from smart_open import open
ModuleNotFoundError: No module named 'smart_open'
[2022-11-18 12:11:21,573] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-18 12:11:21,585] {processor.py:171} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.136 seconds
[2022-11-18 12:11:52,332] {processor.py:163} INFO - Started process (PID=544) to work on /opt/airflow/dags/queue_reader.py
[2022-11-18 12:11:52,336] {processor.py:642} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-18 12:11:52,337] {logging_mixin.py:109} INFO - [2022-11-18 12:11:52,337] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-18 12:11:52,461] {logging_mixin.py:109} INFO - [2022-11-18 12:11:52,459] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from omniParser.omniparser.parser import OmniParser
  File "/opt/airflow/dags/omniParser/omniparser/parser.py", line 6, in <module>
    from smart_open import open
ModuleNotFoundError: No module named 'smart_open'
[2022-11-18 12:11:52,479] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-18 12:11:52,491] {processor.py:171} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.162 seconds
[2022-11-18 12:12:22,615] {processor.py:163} INFO - Started process (PID=598) to work on /opt/airflow/dags/queue_reader.py
[2022-11-18 12:12:22,619] {processor.py:642} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-18 12:12:22,624] {logging_mixin.py:109} INFO - [2022-11-18 12:12:22,624] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-18 12:12:22,864] {logging_mixin.py:109} INFO - [2022-11-18 12:12:22,863] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from omniParser.omniparser.parser import OmniParser
  File "/opt/airflow/dags/omniParser/omniparser/parser.py", line 6, in <module>
    from smart_open import open
ModuleNotFoundError: No module named 'smart_open'
[2022-11-18 12:12:22,879] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-18 12:12:22,896] {processor.py:171} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.296 seconds
[2022-11-18 12:12:53,844] {processor.py:163} INFO - Started process (PID=661) to work on /opt/airflow/dags/queue_reader.py
[2022-11-18 12:12:53,849] {processor.py:642} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-18 12:12:53,851] {logging_mixin.py:109} INFO - [2022-11-18 12:12:53,850] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-18 12:12:53,946] {logging_mixin.py:109} INFO - [2022-11-18 12:12:53,945] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from omniParser.omniparser.parser import OmniParser
  File "/opt/airflow/dags/omniParser/omniparser/parser.py", line 6, in <module>
    from smart_open import open
ModuleNotFoundError: No module named 'smart_open'
[2022-11-18 12:12:53,961] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-18 12:12:53,973] {processor.py:171} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.139 seconds
[2022-11-18 12:13:24,450] {processor.py:163} INFO - Started process (PID=714) to work on /opt/airflow/dags/queue_reader.py
[2022-11-18 12:13:24,456] {processor.py:642} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-18 12:13:24,457] {logging_mixin.py:109} INFO - [2022-11-18 12:13:24,457] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-18 12:13:24,556] {logging_mixin.py:109} INFO - [2022-11-18 12:13:24,555] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from omniParser.omniparser.parser import OmniParser
  File "/opt/airflow/dags/omniParser/omniparser/parser.py", line 6, in <module>
    from smart_open import open
ModuleNotFoundError: No module named 'smart_open'
[2022-11-18 12:13:24,572] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-18 12:13:24,588] {processor.py:171} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.149 seconds
[2022-11-18 12:13:54,763] {processor.py:163} INFO - Started process (PID=767) to work on /opt/airflow/dags/queue_reader.py
[2022-11-18 12:13:54,767] {processor.py:642} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-18 12:13:54,769] {logging_mixin.py:109} INFO - [2022-11-18 12:13:54,768] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-18 12:13:54,864] {logging_mixin.py:109} INFO - [2022-11-18 12:13:54,863] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from omniParser.omniparser.parser import OmniParser
  File "/opt/airflow/dags/omniParser/omniparser/parser.py", line 6, in <module>
    from smart_open import open
ModuleNotFoundError: No module named 'smart_open'
[2022-11-18 12:13:54,879] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-18 12:13:54,890] {processor.py:171} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.140 seconds
[2022-11-18 12:14:25,088] {processor.py:163} INFO - Started process (PID=829) to work on /opt/airflow/dags/queue_reader.py
[2022-11-18 12:14:25,096] {processor.py:642} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-18 12:14:25,105] {logging_mixin.py:109} INFO - [2022-11-18 12:14:25,105] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-18 12:14:25,392] {logging_mixin.py:109} INFO - [2022-11-18 12:14:25,387] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from omniParser.omniparser.parser import OmniParser
  File "/opt/airflow/dags/omniParser/omniparser/parser.py", line 6, in <module>
    from smart_open import open
ModuleNotFoundError: No module named 'smart_open'
[2022-11-18 12:14:25,418] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-18 12:14:25,452] {processor.py:171} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.368 seconds
[2022-11-18 12:14:56,321] {processor.py:163} INFO - Started process (PID=882) to work on /opt/airflow/dags/queue_reader.py
[2022-11-18 12:14:56,322] {processor.py:642} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-18 12:14:56,323] {logging_mixin.py:109} INFO - [2022-11-18 12:14:56,323] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-18 12:14:56,426] {logging_mixin.py:109} INFO - [2022-11-18 12:14:56,424] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from omniParser.omniparser.parser import OmniParser
  File "/opt/airflow/dags/omniParser/omniparser/parser.py", line 6, in <module>
    from smart_open import open
ModuleNotFoundError: No module named 'smart_open'
[2022-11-18 12:14:56,441] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-18 12:14:56,451] {processor.py:171} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.134 seconds
[2022-11-18 12:15:26,796] {processor.py:163} INFO - Started process (PID=936) to work on /opt/airflow/dags/queue_reader.py
[2022-11-18 12:15:26,800] {processor.py:642} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-18 12:15:26,802] {logging_mixin.py:109} INFO - [2022-11-18 12:15:26,802] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-18 12:15:26,923] {logging_mixin.py:109} INFO - [2022-11-18 12:15:26,921] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from omniParser.omniparser.parser import OmniParser
  File "/opt/airflow/dags/omniParser/omniparser/parser.py", line 6, in <module>
    from smart_open import open
ModuleNotFoundError: No module named 'smart_open'
[2022-11-18 12:15:26,942] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-18 12:15:26,953] {processor.py:171} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.168 seconds
[2022-11-18 12:15:57,308] {processor.py:163} INFO - Started process (PID=989) to work on /opt/airflow/dags/queue_reader.py
[2022-11-18 12:15:57,316] {processor.py:642} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-18 12:15:57,317] {logging_mixin.py:109} INFO - [2022-11-18 12:15:57,316] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-18 12:15:57,413] {logging_mixin.py:109} INFO - [2022-11-18 12:15:57,412] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from omniParser.omniparser.parser import OmniParser
  File "/opt/airflow/dags/omniParser/omniparser/parser.py", line 6, in <module>
    from smart_open import open
ModuleNotFoundError: No module named 'smart_open'
[2022-11-18 12:15:57,429] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-18 12:15:57,438] {processor.py:171} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.154 seconds
[2022-11-18 12:16:27,931] {processor.py:163} INFO - Started process (PID=1042) to work on /opt/airflow/dags/queue_reader.py
[2022-11-18 12:16:27,936] {processor.py:642} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-18 12:16:27,939] {logging_mixin.py:109} INFO - [2022-11-18 12:16:27,938] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-18 12:16:28,045] {logging_mixin.py:109} INFO - [2022-11-18 12:16:28,044] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from omniParser.omniparser.parser import OmniParser
  File "/opt/airflow/dags/omniParser/omniparser/parser.py", line 6, in <module>
    from smart_open import open
ModuleNotFoundError: No module named 'smart_open'
[2022-11-18 12:16:28,060] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-18 12:16:28,068] {processor.py:171} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.148 seconds
[2022-11-18 12:16:58,184] {processor.py:163} INFO - Started process (PID=1095) to work on /opt/airflow/dags/queue_reader.py
[2022-11-18 12:16:58,193] {processor.py:642} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-18 12:16:58,200] {logging_mixin.py:109} INFO - [2022-11-18 12:16:58,200] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-18 12:16:58,464] {logging_mixin.py:109} INFO - [2022-11-18 12:16:58,462] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from omniParser.omniparser.parser import OmniParser
  File "/opt/airflow/dags/omniParser/omniparser/parser.py", line 6, in <module>
    from smart_open import open
ModuleNotFoundError: No module named 'smart_open'
[2022-11-18 12:16:58,487] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-18 12:16:58,514] {processor.py:171} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.335 seconds
[2022-11-18 12:17:28,933] {processor.py:163} INFO - Started process (PID=1148) to work on /opt/airflow/dags/queue_reader.py
[2022-11-18 12:17:28,940] {processor.py:642} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-18 12:17:28,947] {logging_mixin.py:109} INFO - [2022-11-18 12:17:28,946] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-18 12:17:29,066] {logging_mixin.py:109} INFO - [2022-11-18 12:17:29,065] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from omniParser.omniparser.parser import OmniParser
  File "/opt/airflow/dags/omniParser/omniparser/parser.py", line 6, in <module>
    from smart_open import open
ModuleNotFoundError: No module named 'smart_open'
[2022-11-18 12:17:29,081] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-18 12:17:29,097] {processor.py:171} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.168 seconds
[2022-11-18 12:17:59,514] {processor.py:163} INFO - Started process (PID=1212) to work on /opt/airflow/dags/queue_reader.py
[2022-11-18 12:17:59,521] {processor.py:642} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-18 12:17:59,524] {logging_mixin.py:109} INFO - [2022-11-18 12:17:59,524] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-18 12:17:59,746] {logging_mixin.py:109} INFO - [2022-11-18 12:17:59,743] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from omniParser.omniparser.parser import OmniParser
  File "/opt/airflow/dags/omniParser/omniparser/parser.py", line 6, in <module>
    from smart_open import open
ModuleNotFoundError: No module named 'smart_open'
[2022-11-18 12:17:59,773] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-18 12:17:59,791] {processor.py:171} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.290 seconds
[2022-11-18 12:18:29,928] {processor.py:163} INFO - Started process (PID=1265) to work on /opt/airflow/dags/queue_reader.py
[2022-11-18 12:18:29,933] {processor.py:642} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-18 12:18:29,936] {logging_mixin.py:109} INFO - [2022-11-18 12:18:29,935] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-18 12:18:30,029] {logging_mixin.py:109} INFO - [2022-11-18 12:18:30,028] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from omniParser.omniparser.parser import OmniParser
  File "/opt/airflow/dags/omniParser/omniparser/parser.py", line 6, in <module>
    from smart_open import open
ModuleNotFoundError: No module named 'smart_open'
[2022-11-18 12:18:30,043] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-18 12:18:30,052] {processor.py:171} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.136 seconds
[2022-11-18 12:19:00,438] {processor.py:163} INFO - Started process (PID=1318) to work on /opt/airflow/dags/queue_reader.py
[2022-11-18 12:19:00,441] {processor.py:642} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-18 12:19:00,443] {logging_mixin.py:109} INFO - [2022-11-18 12:19:00,442] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-18 12:19:00,604] {logging_mixin.py:109} INFO - [2022-11-18 12:19:00,603] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from omniParser.omniparser.parser import OmniParser
  File "/opt/airflow/dags/omniParser/omniparser/parser.py", line 6, in <module>
    from smart_open import open
ModuleNotFoundError: No module named 'smart_open'
[2022-11-18 12:19:00,622] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-18 12:19:00,633] {processor.py:171} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.206 seconds
[2022-11-18 12:19:31,440] {processor.py:163} INFO - Started process (PID=1372) to work on /opt/airflow/dags/queue_reader.py
[2022-11-18 12:19:31,442] {processor.py:642} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-18 12:19:31,443] {logging_mixin.py:109} INFO - [2022-11-18 12:19:31,443] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-18 12:19:31,546] {logging_mixin.py:109} INFO - [2022-11-18 12:19:31,545] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from omniParser.omniparser.parser import OmniParser
  File "/opt/airflow/dags/omniParser/omniparser/parser.py", line 6, in <module>
    from smart_open import open
ModuleNotFoundError: No module named 'smart_open'
[2022-11-18 12:19:31,560] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-18 12:19:31,568] {processor.py:171} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.133 seconds
[2022-11-18 12:20:01,670] {processor.py:163} INFO - Started process (PID=1434) to work on /opt/airflow/dags/queue_reader.py
[2022-11-18 12:20:01,679] {processor.py:642} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-18 12:20:01,680] {logging_mixin.py:109} INFO - [2022-11-18 12:20:01,680] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-18 12:20:01,882] {logging_mixin.py:109} INFO - [2022-11-18 12:20:01,879] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from omniParser.omniparser.parser import OmniParser
  File "/opt/airflow/dags/omniParser/omniparser/parser.py", line 6, in <module>
    from smart_open import open
ModuleNotFoundError: No module named 'smart_open'
[2022-11-18 12:20:01,906] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-18 12:20:01,920] {processor.py:171} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.254 seconds
[2022-11-18 12:20:32,025] {processor.py:163} INFO - Started process (PID=1487) to work on /opt/airflow/dags/queue_reader.py
[2022-11-18 12:20:32,026] {processor.py:642} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-18 12:20:32,036] {logging_mixin.py:109} INFO - [2022-11-18 12:20:32,036] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-18 12:20:32,331] {logging_mixin.py:109} INFO - [2022-11-18 12:20:32,324] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from omniParser.omniparser.parser import OmniParser
  File "/opt/airflow/dags/omniParser/omniparser/parser.py", line 6, in <module>
    from smart_open import open
ModuleNotFoundError: No module named 'smart_open'
[2022-11-18 12:20:32,364] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-18 12:20:32,391] {processor.py:171} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.379 seconds
[2022-11-18T12:28:52.159+0000] {processor.py:154} INFO - Started process (PID=50) to work on /opt/airflow/dags/queue_reader.py
[2022-11-18T12:28:52.171+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-18T12:28:52.178+0000] {logging_mixin.py:137} INFO - [2022-11-18T12:28:52.178+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-18T12:28:53.718+0000] {logging_mixin.py:137} INFO - [2022-11-18T12:28:53.713+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from omniParser.omniparser.parser import OmniParser
  File "/opt/airflow/dags/omniParser/omniparser/parser.py", line 6, in <module>
    from smart_open import open
ModuleNotFoundError: No module named 'smart_open'
[2022-11-18T12:28:53.722+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-18T12:28:53.818+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/queue_reader.py took 1.685 seconds
[2022-11-18T12:29:23.933+0000] {processor.py:154} INFO - Started process (PID=107) to work on /opt/airflow/dags/queue_reader.py
[2022-11-18T12:29:23.935+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-18T12:29:23.937+0000] {logging_mixin.py:137} INFO - [2022-11-18T12:29:23.936+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-18T12:29:24.060+0000] {logging_mixin.py:137} INFO - [2022-11-18T12:29:24.059+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from omniParser.omniparser.parser import OmniParser
  File "/opt/airflow/dags/omniParser/omniparser/parser.py", line 6, in <module>
    from smart_open import open
ModuleNotFoundError: No module named 'smart_open'
[2022-11-18T12:29:24.061+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-18T12:29:24.084+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.157 seconds
[2022-11-18T12:29:55.394+0000] {processor.py:154} INFO - Started process (PID=163) to work on /opt/airflow/dags/queue_reader.py
[2022-11-18T12:29:55.422+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-18T12:29:55.425+0000] {logging_mixin.py:137} INFO - [2022-11-18T12:29:55.425+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-18T12:29:58.854+0000] {logging_mixin.py:137} INFO - [2022-11-18T12:29:58.807+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from omniParser.omniparser.parser import OmniParser
  File "/opt/airflow/dags/omniParser/omniparser/parser.py", line 6, in <module>
    from smart_open import open
ModuleNotFoundError: No module named 'smart_open'
[2022-11-18T12:29:58.859+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-18T12:29:59.112+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/queue_reader.py took 3.778 seconds
[2022-11-18T12:30:29.335+0000] {processor.py:154} INFO - Started process (PID=221) to work on /opt/airflow/dags/queue_reader.py
[2022-11-18T12:30:29.348+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-18T12:30:29.351+0000] {logging_mixin.py:137} INFO - [2022-11-18T12:30:29.351+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-18T12:30:29.870+0000] {logging_mixin.py:137} INFO - [2022-11-18T12:30:29.867+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from omniParser.omniparser.parser import OmniParser
  File "/opt/airflow/dags/omniParser/omniparser/parser.py", line 6, in <module>
    from smart_open import open
ModuleNotFoundError: No module named 'smart_open'
[2022-11-18T12:30:29.877+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-18T12:30:29.971+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.651 seconds
[2022-11-18T12:31:01.013+0000] {processor.py:154} INFO - Started process (PID=277) to work on /opt/airflow/dags/queue_reader.py
[2022-11-18T12:31:01.016+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-18T12:31:01.017+0000] {logging_mixin.py:137} INFO - [2022-11-18T12:31:01.017+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-18T12:31:01.213+0000] {logging_mixin.py:137} INFO - [2022-11-18T12:31:01.211+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from omniParser.omniparser.parser import OmniParser
  File "/opt/airflow/dags/omniParser/omniparser/parser.py", line 6, in <module>
    from smart_open import open
ModuleNotFoundError: No module named 'smart_open'
[2022-11-18T12:31:01.214+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-18T12:31:01.291+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.286 seconds
[2022-11-18T12:31:32.010+0000] {processor.py:154} INFO - Started process (PID=334) to work on /opt/airflow/dags/queue_reader.py
[2022-11-18T12:31:32.015+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-18T12:31:32.018+0000] {logging_mixin.py:137} INFO - [2022-11-18T12:31:32.017+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-18T12:31:32.225+0000] {logging_mixin.py:137} INFO - [2022-11-18T12:31:32.223+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from omniParser.omniparser.parser import OmniParser
  File "/opt/airflow/dags/omniParser/omniparser/parser.py", line 6, in <module>
    from smart_open import open
ModuleNotFoundError: No module named 'smart_open'
[2022-11-18T12:31:32.225+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-18T12:31:32.254+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.253 seconds
[2022-11-18T12:32:08.329+0000] {processor.py:154} INFO - Started process (PID=379) to work on /opt/airflow/dags/queue_reader.py
[2022-11-18T12:32:08.391+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-18T12:32:08.396+0000] {logging_mixin.py:137} INFO - [2022-11-18T12:32:08.396+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-18T12:32:11.602+0000] {logging_mixin.py:137} INFO - [2022-11-18T12:32:11.550+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from omniParser.omniparser.parser import OmniParser
  File "/opt/airflow/dags/omniParser/omniparser/parser.py", line 6, in <module>
    from smart_open import open
ModuleNotFoundError: No module named 'smart_open'
[2022-11-18T12:32:11.647+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-18T12:32:12.548+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/queue_reader.py took 4.261 seconds
[2022-11-18T12:33:00.527+0000] {processor.py:154} INFO - Started process (PID=445) to work on /opt/airflow/dags/queue_reader.py
[2022-11-18T12:33:00.530+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-18T12:33:00.531+0000] {logging_mixin.py:137} INFO - [2022-11-18T12:33:00.531+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-18T12:33:01.060+0000] {logging_mixin.py:137} INFO - [2022-11-18T12:33:01.058+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from omniParser.omniparser.parser import OmniParser
  File "/opt/airflow/dags/omniParser/omniparser/parser.py", line 6, in <module>
    from smart_open import open
ModuleNotFoundError: No module named 'smart_open'
[2022-11-18T12:33:01.061+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-18T12:33:01.105+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/queue_reader.py took 0.586 seconds
[2022-11-18T12:33:39.997+0000] {processor.py:154} INFO - Started process (PID=492) to work on /opt/airflow/dags/queue_reader.py
[2022-11-18T12:33:40.057+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-18T12:33:40.089+0000] {logging_mixin.py:137} INFO - [2022-11-18T12:33:40.089+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-18T12:33:48.077+0000] {logging_mixin.py:137} INFO - [2022-11-18T12:33:47.944+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from omniParser.omniparser.parser import OmniParser
  File "/opt/airflow/dags/omniParser/omniparser/parser.py", line 6, in <module>
    from smart_open import open
ModuleNotFoundError: No module named 'smart_open'
[2022-11-18T12:33:48.105+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-18T12:33:50.386+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/queue_reader.py took 9.749 seconds
[2022-11-18T12:34:40.373+0000] {processor.py:154} INFO - Started process (PID=536) to work on /opt/airflow/dags/queue_reader.py
[2022-11-18T12:34:40.516+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/queue_reader.py for tasks to queue
[2022-11-18T12:34:40.644+0000] {logging_mixin.py:137} INFO - [2022-11-18T12:34:40.643+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/queue_reader.py
[2022-11-18T12:34:44.530+0000] {logging_mixin.py:137} INFO - [2022-11-18T12:34:44.507+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/queue_reader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/queue_reader.py", line 5, in <module>
    from omniParser.omniparser.parser import OmniParser
  File "/opt/airflow/dags/omniParser/omniparser/parser.py", line 6, in <module>
    from smart_open import open
ModuleNotFoundError: No module named 'smart_open'
[2022-11-18T12:34:44.557+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/queue_reader.py
[2022-11-18T12:34:45.432+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/queue_reader.py took 4.556 seconds
